### ISSUE TITLE
WES:  Amend the VCF imported into Moka to include the # homo counts in Exac from Ingenuity

### ISSUE THREAD

**Issue by SueLillis** [woook/moka-fe#202]
Please can the VCF containing variant information imported from Ingenuity into Moka include a column for recording the number of homo. counts in Exac? This would save lots of time when analysing

**Comment by andyb3** [comment]
For some reason Ingenuity don't output ExAC info into the VCF, but we can pull in this info via the ExAC API

**Comment by woook** [comment]
Let's use mygene.info rather than the ExAC API

**Comment by andyb3** [comment]
There is still no ExAC/gnomAD info in the VCF and this has been identified as a priority issue for the lab. Assuming this would now be gnomAD hom count rather than ExAC?

**Comment by woook** [comment]
Would it be too much to incorp #298 at the same time?
Is that data in the API?

**Comment by woook** [comment]
Use GEL annotations from cellbase

**Comment by AmyAmelia** [comment]
Response from GeL RE: adding Hom counts to cell base <- Does not look promising in the near future. 
"This is not an easy thing to implement, because the contents of this field are processed once and stored from the ExAC/Gnomad releases, so this is not trivial to retrieve.
the core issue with this is that some samples are excluded from each individual variant site based on sequencing depth/quality/poor alignments etc. so raw counts is far more likely to be misleading
So it is not possible to recreate the raw counts without completely revisiting the data source, as well as changing the API
The assumption is from this side that the raw count cannot be used independently of frequency to ensure that the results do not lead to over-confident filtering (e.g. 1 in a large population is still 100% if the rest are excluded), and as datasets scale the raw count becomes increasingly less useful without the frequency.
I will pass this on as a feature request, but I would not expect it to be a feature that is implemented soon. I will either update your ticket or let you know directly once I have any update"

interim update, Javi (CellBase project manager) estimates it would take ~weeks to process all the VCFs to obtain hom counts reliably for every variant based on the current environment, not including time for the feature to be coded up and tested, so this will be a long time
That is very much a rough estimate, but it's on the backlog now

**Comment by aledj2** [comment]
Can this be added as a custom annotation before Ingenuity? Maybe reopen as a new issue.
