### ISSUE TITLE
WES coverage report error message

### ISSUE THREAD

**Issue by MattiasJanssonviapath** [woook/moka-fe#304]
We get an error message when trying to make a coverage report for TestID 737.

Cheers, /Matt

**Comment by aledj2** [comment]
It's because the following genes are present:DWS (HGNC:3088) us a phenotype only gene
MIR17HG (HGNC:23564) is a RNA, long non-coding gene
MRT4 (HGNC:33243) is a phenotype only gene
RNU4ATAC (HGNC:34016) is a RNA,small nuclear gene

**Comment by aledj2** [comment]
oops. pressed send too soon. 
We already ignore phenotype only genes, it's the RNA genes which are causing the issue. I feel like recently we had a issue where there was not coverage information for RNA genes so we made a change to the code so that we were not expecting coverage data for RNA genes. Now we have RNA genes that does have coverage. will have a look. How urgent is this?

**Comment by MattiasJanssonviapath** [comment]
Needed before end of the month.

Cheers, /Matt

**Comment by aledj2** [comment]
This should work now. re-open this issue if it doesn't! We shouldn't get this issue in the future either!
