### ISSUE TITLE
Transfering feature extraction files

### ISSUE THREAD

**Issue by ClaRomano** [woook/moka-fe#445]
Would it be possible to restore Syncback to transfer feature extraction and QC files from the scanner PC to the analysis computers following the array scanning?
Thanks.

**Comment by andyb3** [comment]
I've just discussed this with Wook. It's not possible to install syncback on the new trust machines. However as a compromise we could potentially use syncback to upload files from the scanner PC to a server on the internet. You would then be able to manually download the files from the server onto your PCs.

**Comment by ClaRomano** [comment]
Hi Andy,
Thanks for getting back so promptly.
Me and Mike are fine manually downloading the files from the server.

Thanks,

Claudia

Claudia Romano
Medical Technical Officer 2 | Viapath
Genetics department
5th floor Tower Wing | Guy’s Hospital | London | SE1 9RT
claudia.romano@viapath.co.uk<mailto:claudia.romano@viapath.co.uk>
Tel: +44 (0) 207 181706

**Comment by woook** [comment]
Dear Claudia (and Mike)
Please raise a ticket with IT asking for Filezilla to be installed on your PCs.

Thanks.

**Comment by woook** [comment]
Please could you also send me (Wook) your PC names.

**Comment by woook** [comment]
1. Scanner

**Comment by andyb3** [comment]
Claudia and Mike have moved desks since the above requests were made. Have requested new Filezilla installations and SFTP access to genomics.viapath.co.uk.

**Comment by andyb3** [comment]
The above requests were rejected by IT. 

Apparently Filezilla must be requested through the following form: https://gstt.service-now.com/ess/order-software.do
And in the request we need to include "a) Details of what is being sent or retrieved ? b) Business justification for the use of Filezilla. This is because, the software is still under review. "

SFTP access requests were rejected:
"Thanks for contacting us regarding the above Tickets to use SFTP to transfer and upload files. We have reviewed your request and based on GSTT Information security measures, data handing is a paramount responsibility for the Trust and in the light of security any traffic  either inbound our outbound has to go through a secure channel. Information Security team do not treat SFTP as a secure method for transferring data in or out of GSTT network. We have other recommended method that we promote and one of them is NHS.net email SFTP (refer to the link below) or Egress email switch which can be requested as per user."

**Comment by AmyAmelia** [comment]
Request for binfx trust machines to have SFTP and SSH access.

**Comment by andyb3** [comment]
Above request made on 17/05/18. Awaiting response.

**Comment by woook** [comment]
Raise a new ticket asking for a secondary user (array team) to have  FTP access

**Comment by woook** [comment]
Old files being backed up to nexus which solves the free space issue on the scanner PC

**Comment by andyb3** [comment]
[MoveITServiceRequest v1.1.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0d198163e424001409b511/125516c66e82c728ace21e0d46c59b8c26abb79a8afba94aa758c291385322603d44b57a3ed4a164fd52690e050a1de853524d41aef9dd2aaee368748f0a5ee9836d5f76c33f11fdea871bad1da862da11d1e9e1d30695aa2f2ff58a88453f1b06188cfc5930a2914bc958e406.docx)

**Comment by aledj2** [comment]
For now keep using USB sticks. Will be setting up an upload to DNAnexus so could download from there in future.
