### ISSUE TITLE
unable to report tissue twins

### ISSUE THREAD

**Issue by cdonaghue** [woook/moka-fe#469]
I have a couple of tissues which have gone wrong in MOKA, possibly because there were brackets in the names (which I have now removed).  They don’t open using the spec number, print blank result sheets or crash MOKA in a random fashion.
 
Twins 18/05357 and 18/05356 FROST

I need to report these by 12/03/18

**Comment by woook** [comment]
Due to first name being >30 characters and dbo_Patients_Table design has 30 character limit for firstname. This limit has been extended to 50 characters in Geneworks and therefore have forced a refresh of dbo_Patients_Table to propagate across. Should no longer recur.

Results for these twins have been printed.
